"use client"

import { Inter } from "next/font/google";
import ApolloProviderWrapper from "./components/Apollo/apolloProviderWrapper";
import Navbar from "./components/navbar";
import Layouts from "./components/layouts";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const pathname = usePathname();
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloProviderWrapper>
          {/* <Layouts> */}
          <main className={pathname === '/games' ? "container wrapper layouts" : (pathname === '/signup' ? "container wrapper layout" : "container wrapper")}>
            <div className={pathname === '/games' ? "before" : (pathname === '/signup' ? "container wrapper after" : "")}></div>
            <Navbar />
            {children}
          </main>
          {/* </Layouts> */}
        </ApolloProviderWrapper>
      </body>
    </html>
  );
}
