import { Inter } from "next/font/google";
import ApolloProviderWrapper from "./components/Apollo/apolloProviderWrapper";
import Navbar from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloProviderWrapper>
          <main className="container wrapper">
            <Navbar />
            {children}
          </main>
        </ApolloProviderWrapper>
      </body>
    </html>
  );
}
