"""Added website attribute to Game model

Revision ID: 110a15521e70
Revises: c6ab90766372
Create Date: 2024-08-12 16:46:02.101485

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "110a15521e70"
down_revision = "c6ab90766372"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.add_column(sa.Column("website", sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.drop_column("website")

    # ### end Alembic commands ###
