"""Added followers table

Revision ID: 1f4759ae743f
Revises: 59dfb69c2cab
Create Date: 2024-07-19 20:29:30.969314

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1f4759ae743f"
down_revision = "59dfb69c2cab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "followers",
        sa.Column("follower_id", sa.Integer(), nullable=True),
        sa.Column("followee_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["followee_id"], ["users.id"], name=op.f("fk_followers_followee_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["follower_id"], ["users.id"], name=op.f("fk_followers_follower_id_users")
        ),
    )
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.add_column(sa.Column("followers", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("following", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.drop_column("following")
        batch_op.drop_column("followers")

    op.drop_table("followers")
    # ### end Alembic commands ###
