"""Changed 4 column constraints to nullable

Revision ID: 2c77456e21e1
Revises: 8aaf2fea4fff
Create Date: 2024-08-02 00:20:03.433474

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2c77456e21e1"
down_revision = "8aaf2fea4fff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.alter_column(
            "about", existing_type=sa.VARCHAR(length=1000), nullable=True
        )
        batch_op.alter_column(
            "publisher", existing_type=sa.VARCHAR(length=250), nullable=True
        )
        batch_op.alter_column("developer", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.alter_column("developer", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "publisher", existing_type=sa.VARCHAR(length=250), nullable=False
        )
        batch_op.alter_column(
            "about", existing_type=sa.VARCHAR(length=1000), nullable=False
        )

    # ### end Alembic commands ###
