"""Changed 4 column constraints to not nullable

Revision ID: 8f9895dca39f
Revises: 2c77456e21e1
Create Date: 2024-08-02 00:24:39.395564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9895dca39f'
down_revision = '2c77456e21e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('about',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
        batch_op.alter_column('publisher',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('developer',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('developer',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('publisher',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('about',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)

    # ### end Alembic commands ###
