"""Added likes and dislikes columns to review table, added new table ReviewLikes

Revision ID: b276a4361099
Revises: f10ab4f9f94c
Create Date: 2024-08-05 21:09:00.614479

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b276a4361099"
down_revision = "f10ab4f9f94c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review_likes",
        sa.Column("review_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("to_like", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["reviews.id"],
            name=op.f("fk_review_likes_review_id_reviews"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_review_likes_user_id_users")
        ),
        sa.PrimaryKeyConstraint("review_id", "user_id"),
    )
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.add_column(sa.Column("likes", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("dislikes", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.drop_column("dislikes")
        batch_op.drop_column("likes")

    op.drop_table("review_likes")
    # ### end Alembic commands ###
