"""Added Signup and Login logic

Revision ID: c35dd65eb73e
Revises: 1f4759ae743f
Create Date: 2024-07-22 21:05:52.418458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c35dd65eb73e'
down_revision = '1f4759ae743f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(), nullable=False))
        batch_op.alter_column('profilePic',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('profilePic',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
