"""Updated image_url column

Revision ID: f10ab4f9f94c
Revises: 13ec3407c69c
Create Date: 2024-08-05 16:34:08.836249

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f10ab4f9f94c"
down_revision = "13ec3407c69c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.alter_column(
            "image_url", existing_type=postgresql.ARRAY(sa.VARCHAR()), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.alter_column(
            "image_url", existing_type=postgresql.ARRAY(sa.VARCHAR()), nullable=True
        )

    # ### end Alembic commands ###
